const MONGO_ADDRESS = '192.168.1.119';

const USERS_MONGO_URL = `mongodb://${MONGO_ADDRESS}:27017/slowitdown`;
const MONGO_URL = `mongodb://${MONGO_ADDRESS}:27017/slowitdown`;

const VERIFY_TOKENS_COLLECTION = 'UserVerificationTokens';
const USERS_COLLECTION = 'User';
const HIGHSCORES_COLLECTION = 'Highscores';
const PUSH_NOTIFICATION_TOKENS = 'PushNotificationTokens';

module.exports = {
  USERS_MONGO_URL,
  MONGO_URL,
  VERIFY_TOKENS_COLLECTION,
  USERS_COLLECTION,
  HIGHSCORES_COLLECTION,
  PUSH_NOTIFICATION_TOKENS
}